/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code.lms;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author sajeewa
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
        connect = DBconnect.connect();
    }
    Connection connect = null;
    PreparedStatement prt = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l_name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        f_name = new javax.swing.JTextField();
        password1 = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        create_account = new javax.swing.JButton();
        login = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_name.setBackground(new java.awt.Color(204, 204, 204));
        l_name.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        l_name.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(l_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 290, 280, 50));

        email.setBackground(new java.awt.Color(204, 204, 204));
        email.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 580, 50));

        f_name.setBackground(new java.awt.Color(204, 204, 204));
        f_name.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        f_name.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(f_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 280, 50));

        password1.setBackground(new java.awt.Color(204, 204, 204));
        password1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        password1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 500, 280, 60));

        password.setBackground(new java.awt.Color(204, 204, 204));
        password.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 502, 270, 60));

        jCheckBox1.setBackground(new java.awt.Color(204, 204, 204));
        jCheckBox1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 204, 0));
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, -1, 20));

        create_account.setBackground(new java.awt.Color(0, 0, 255));
        create_account.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        create_account.setForeground(new java.awt.Color(255, 255, 255));
        create_account.setText("Create Account");
        create_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_accountActionPerformed(evt);
            }
        });
        jPanel1.add(create_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 660, 260, 60));

        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 740, 50, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\java_test\\LMS\\src\\main\\java\\imsges\\signup_4.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 840));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 850));

        setSize(new java.awt.Dimension(1429, 876));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginMouseClicked

    private void create_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_accountActionPerformed
        String firstname, lastname, email, password, password1;
        firstname = f_name.getText();
        lastname = l_name.getText();
        email = this.email.getText();
        password = this.password.getText();
        password1 = this.password1.getText();

        if (password.equals(password1)) {
            try {
                String sql = "INSERT INTO person(first_name, last_name,email,password) VALUES('" + firstname + "','" + lastname + "','" + email + "','" + password + "')";
                prt = connect.prepareStatement(sql);
                prt.execute();
                JOptionPane.showMessageDialog(null, "Insert succesfully");
                f_name.setText("");
                l_name.setText("");
                this.email.setText("");
                this.password.setText("");
                this.password1.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "password not equals");
        }


    }//GEN-LAST:event_create_accountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create_account;
    private javax.swing.JTextField email;
    private javax.swing.JTextField f_name;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField l_name;
    private javax.swing.JLabel login;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password1;
    // End of variables declaration//GEN-END:variables
}
